"""First-run setup wizard: a localhost web form that writes config.yaml and
answers.md. Personal data stays on this machine; secrets (Slack, IMAP) are
deliberately out of scope and stay in scripts/.env — see the README.

Pure builders (build_config_yaml / build_answers_md / write_outputs) are
separated from the HTTP layer so they can be tested without a browser.
"""
from __future__ import annotations

import html
import os
import re
import threading
import time
import webbrowser
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from secrets import token_urlsafe
from typing import Any
from urllib.parse import parse_qs, urlparse

import yaml

WizardState = dict[str, Any]

SOURCE_KINDS = ["greenhouse", "lever", "ashby", "workable",
                "smartrecruiters", "recruitee", "adzuna"]


def _csv(value: str) -> list[str]:
    return [x.strip() for x in str(value or "").split(",") if x.strip()]


def build_config_yaml(state: WizardState) -> str:
    """config.yaml text from wizard state. Only wizard-scope sections are
    emitted; everything else keeps the code defaults (documented in
    config.example.yaml). Safety: autonomy is pinned to review/no-live."""
    sources = []
    tokens: dict[str, list[str]] = {}
    for line in str(state.get("source_tokens", "")).splitlines():
        line = line.strip()
        if not line or ":" not in line:
            continue
        kind, token = line.split(":", 1)
        tokens.setdefault(kind.strip(), []).append(token.strip())
    for kind in state.get("sources", []):
        for token in tokens.get(kind, [""]):
            sources.append({"kind": kind, "token": token})

    variants = []
    for v in state.get("resume_variants", []):
        if str(v.get("path", "")).strip():
            variants.append({
                "keywords": _csv(v.get("keywords", "")),
                "path": str(v["path"]).strip(),
            })

    families: dict[str, dict] = {}
    for name, fam in (state.get("families") or {}).items():
        families[name] = {
            "keywords": _csv(fam.get("keywords", "")),
            "identity": str(fam.get("identity", "")).strip(),
            "craft": str(fam.get("craft", "")).strip(),
            "closing_mix": str(fam.get("closing_mix", "")).strip(),
            "marker": str(fam.get("marker", "")).strip().lower(),
        }
    projects = []
    for pr in state.get("projects", []):
        if str(pr.get("text", "")).strip():
            projects.append({
                "keywords": _csv(pr.get("keywords", "")),
                "text": str(pr["text"]).strip(),
            })

    profile: dict[str, Any] = {
        "name": str(state.get("full_name") or
                    f"{state.get('first_name', '')} {state.get('last_name', '')}").strip(),
        "email": str(state.get("email", "")).strip(),
        "phone": str(state.get("phone", "")).strip(),
        "location": str(state.get("location", "")).strip(),
        "website": str(state.get("website", "")).strip(),
        "linkedin": str(state.get("linkedin", "")).strip(),
        "pronouns": str(state.get("pronouns", "")).strip(),
        "summary": str(state.get("facts_background", "")).strip(),
        "titles": _csv(state.get("titles", "")),
        "skills": _csv(state.get("skills", "")),
        "locations": ([] if state.get("remote_ok") == "yes" and
                      not _csv(state.get("locations", ""))
                      else _csv(state.get("locations", ""))),
        "resume_path": str(state.get("resume_default", "")).strip(),
        "answers_path": "answers.md",
    }
    if variants:
        profile["resume_variants"] = variants

    data = {
        "profile": profile,
        "autonomy": {"mode": "review", "live_submit": False},
        "filters": {"exclude_keywords": _csv(state.get("exclude_keywords", ""))},
        "coverletter": {
            "default_family": (next(iter(families)) if families else ""),
            "families": families,
            "projects": projects,
        },
        "sources": sources,
    }
    header = (
        "# Generated by `jobagent setup` on {}.\n"
        "# Safe defaults: nothing is submitted until you set autonomy.mode: auto\n"
        "# AND autonomy.live_submit: true. Advanced settings (Slack, email\n"
        "# verification, scoring weights, schedules) keep their defaults —\n"
        "# see config.example.yaml for every option, and re-run\n"
        "# `jobagent setup` any time to edit this file.\n"
    ).format(time.strftime("%Y-%m-%d %H:%M"))
    return header + yaml.safe_dump(data, sort_keys=False, allow_unicode=True,
                                   default_flow_style=False)


def build_answers_md(state: WizardState) -> str:
    """answers.md text from wizard state, in the format AnswerBook parses
    (## Fields / ## Questions / ## Context)."""
    auth_text = {
        "yes": "Authorized to work in the US",
        "yes_limited": "Authorized to work with a time limit",
        "no": "Not currently authorized",
    }.get(str(state.get("auth_status", "")), "")
    sponsorship = "Yes" if state.get("sponsorship") == "yes" else "No"

    lines = ["# Application Answers", "",
             "# Generated by `jobagent setup`. Add more lines any time —",
             "# the filler holds any REQUIRED field it cannot answer from here.",
             "", "## Fields"]
    for key, src in [
        ("first_name", "first_name"), ("last_name", "last_name"),
        ("full_name", "full_name"), ("email", "email"), ("phone", "phone"),
        ("location", "location"), ("state", "state"),
        ("linkedin", "linkedin"), ("website", "website"), ("github", "github"),
        ("pronouns", "pronouns"), ("phonetic_name", "phonetic_name"),
    ]:
        val = str(state.get(src, "")).strip()
        if val:
            lines.append(f"- {key}: {val}")
    lines.append(f"- work_authorization: {auth_text}")
    lines.append(f"- require_sponsorship: {sponsorship}")
    notes = str(state.get("auth_notes", "")).strip()
    if notes:
        lines.append(f"- work_authorization_notes: {notes}")
    lines += [
        "Voluntary EEO questions. Leave as-is to decline, or edit.",
        "- gender: Decline to self-identify",
        "- hispanic_latino: Decline to self-identify",
        "- race: Decline to self-identify",
        "- veteran_status: Decline to self-identify",
        "- disability_status: Decline to self-identify",
        "", "## Questions",
    ]
    standard = str(state.get("facts_standard", "")).strip()
    if standard:
        lines.append(standard)
    lines += ["", "## Context"]
    for part in ("facts_background", "facts_projects"):
        val = str(state.get(part, "")).strip()
        if val:
            lines.append(val)
    return "\n".join(lines).rstrip() + "\n"


def _atomic_write(path: Path, text: str) -> None:
    if path.exists():
        bak = path.with_name(f"{path.name}.bak-{time.strftime('%Y%m%d-%H%M%S')}")
        bak.write_text(path.read_text(encoding="utf-8"), encoding="utf-8")
    tmp = path.with_name(path.name + ".tmp")
    tmp.write_text(text, encoding="utf-8")
    os.replace(tmp, path)


def write_outputs(state: WizardState, config_path: Path,
                  answers_path: Path) -> list[str]:
    config_path = Path(config_path)
    answers_path = Path(answers_path)
    _atomic_write(config_path, build_config_yaml(state))
    _atomic_write(answers_path, build_answers_md(state))
    return [str(config_path), str(answers_path)]


def state_from_existing(config_path: Path, answers_path: Path) -> WizardState:
    """Pre-seed the wizard from existing files so re-running edits them.
    Best-effort: unreadable/missing files just mean an empty seed."""
    state: WizardState = {}
    try:
        from .config import load_config
        cfg = load_config(config_path)
    except Exception:
        return state
    p = cfg.profile
    parts = p.name.split(None, 1)
    state.update({
        "first_name": parts[0] if parts else "",
        "last_name": parts[1] if len(parts) > 1 else "",
        "full_name": p.name, "email": p.email, "phone": p.phone,
        "location": p.location, "website": p.website, "linkedin": p.linkedin,
        "pronouns": p.pronouns,
        "titles": ", ".join(p.titles), "skills": ", ".join(p.skills),
        "locations": ", ".join(p.locations),
        "remote_ok": "yes" if not p.locations else "no",
        "exclude_keywords": ", ".join(cfg.filters.exclude_keywords),
        "resume_default": p.resume_path,
        "resume_variants": [
            {"keywords": ", ".join(v.keywords), "path": v.path}
            for v in p.resume_variants
        ],
        "sources": sorted({s.kind for s in cfg.sources}),
        "source_tokens": "\n".join(
            f"{s.kind}:{s.token}" for s in cfg.sources if s.token),
        "families": {
            name: {"keywords": ", ".join(f.keywords), "identity": f.identity,
                   "craft": f.craft, "closing_mix": f.closing_mix,
                   "marker": f.marker}
            for name, f in cfg.coverletter.families.items()
        },
        "projects": [
            {"keywords": ", ".join(pr.keywords), "text": pr.text}
            for pr in cfg.coverletter.projects
        ],
        "facts_background": p.summary,
    })
    return state


# --------------------------------------------------------------------------
# HTTP layer. One process, one user, in-memory state; nothing is written
# until the final Review step's "Write files" action.
# --------------------------------------------------------------------------

STEPS = [
    ("basics",    "1 · Basics",        ["first_name", "last_name", "email", "phone"]),
    ("workauth",  "2 · Work auth",     ["auth_status", "sponsorship"]),
    ("targeting", "3 · Targeting",     ["titles"]),
    ("resumes",   "4 · Resumes",       ["resume_default"]),
    ("letters",   "5 · Cover letters", []),   # validated by _letters_ok()
    ("facts",     "6 · Facts",         []),
    ("review",    "7 · Review",        []),
]

_STYLE = """
:root { --bg:#f6f7f9; --card:#fff; --ink:#1a1d21; --muted:#6b7280;
  --line:#e5e7eb; --accent:#2563eb; --accent-ink:#fff; --done:#16a34a;
  --chip:#eef2ff; }
@media (prefers-color-scheme: dark) { :root { --bg:#111418; --card:#1a1f26;
  --ink:#e8eaed; --muted:#9aa3af; --line:#2a313a; --accent:#3b82f6;
  --chip:#1e2a45; } }
* { box-sizing:border-box; margin:0; }
body { font:15px/1.55 -apple-system,"Segoe UI",sans-serif; background:var(--bg);
  color:var(--ink); padding:24px; }
.frame { max-width:880px; margin:0 auto; }
.app { background:var(--card); border:1px solid var(--line); border-radius:14px;
  overflow:hidden; box-shadow:0 1px 4px rgba(0,0,0,.06); }
header.bar { padding:18px 26px 0; }
header.bar h1 { font-size:17px; font-weight:650; }
header.bar .url { font-size:12px; color:var(--muted);
  font-family:ui-monospace,monospace; margin-top:2px; }
.steps { display:flex; gap:4px; padding:16px 26px; flex-wrap:wrap;
  border-bottom:1px solid var(--line); }
.step { border:1px solid var(--line); color:var(--muted); border-radius:999px;
  padding:5px 12px; font-size:12.5px; text-decoration:none; }
.step.active { background:var(--accent); border-color:var(--accent);
  color:var(--accent-ink); }
.step.done { color:var(--done); border-color:var(--done); }
.step.done::before { content:"\\2713 "; }
main { padding:24px 26px 8px; min-height:380px; }
main h2 { font-size:15.5px; font-weight:650; margin-bottom:4px; }
main p.hint { color:var(--muted); font-size:13px; margin-bottom:18px; }
.grid { display:grid; grid-template-columns:1fr 1fr; gap:14px 18px; }
.grid .wide { grid-column:1 / -1; }
label { display:block; font-size:12.5px; font-weight:600; margin-bottom:5px; }
label .req { color:#dc2626; }
input[type=text], textarea, select { width:100%; padding:8px 10px;
  border:1px solid var(--line); border-radius:8px; background:var(--bg);
  color:var(--ink); font:inherit; font-size:13.5px; }
textarea { resize:vertical; }
::placeholder { color:#9ca3af; font-style:italic; }
.radio-row, .check-row { display:flex; gap:18px; flex-wrap:wrap; padding:4px 0;
  font-size:13.5px; }
.radio-row label, .check-row label { font-weight:400; display:flex; gap:6px;
  align-items:center; margin:0; }
.note { background:var(--chip); border-radius:8px; padding:10px 12px;
  font-size:12.5px; color:var(--muted); margin-top:16px; }
.fam { border:1px solid var(--line); border-radius:10px; padding:14px 16px;
  margin-bottom:12px; }
.fam h3 { font-size:13.5px; margin-bottom:10px; }
.review td { padding:4px 10px 4px 0; font-size:13px; vertical-align:top; }
.review td:first-child { color:var(--muted); white-space:nowrap; }
footer.nav { display:flex; justify-content:space-between; align-items:center;
  padding:18px 26px 22px; border-top:1px solid var(--line); margin-top:18px; }
.btn { font:inherit; font-size:13.5px; padding:8px 18px; border-radius:8px;
  border:1px solid var(--line); background:transparent; color:var(--ink);
  cursor:pointer; text-decoration:none; }
.btn.primary { background:var(--accent); border-color:var(--accent);
  color:var(--accent-ink); font-weight:600; }
"""

# Appended only when a step re-renders with errors, so the word never appears
# on a clean page (tests rely on that to detect validation).
_STYLE_ERR = """
input.invalid, textarea.invalid { border-color:#dc2626;
  background:rgba(220,38,38,.06); }
.radio-row.invalid { outline:1.5px solid #dc2626; outline-offset:4px;
  border-radius:6px; }
.errmsg { color:#dc2626; font-size:12.5px; }
"""


def _esc(v: Any) -> str:
    return html.escape(str(v or ""), quote=True)


def _inp(state: WizardState, name: str, placeholder: str = "",
         errors: set | None = None, label: str = "", required: bool = False,
         wide: bool = False) -> str:
    val = _esc(state.get(name, ""))
    cls = ' class="invalid"' if errors and name in errors else ""
    req = ' <span class="req">*</span>' if required else ""
    value = f' value="{val}"' if val else ""
    div = ' class="wide"' if wide else ""
    return (f'<div{div}><label>{label}{req}</label>'
            f'<input type="text" name="{name}"{value}'
            f' placeholder="{_esc(placeholder)}"{cls}></div>')


def _ta(state: WizardState, name: str, placeholder: str = "",
        errors: set | None = None, label: str = "", required: bool = False,
        rows: int = 3) -> str:
    val = _esc(state.get(name, ""))
    cls = ' class="invalid"' if errors and name in errors else ""
    req = ' <span class="req">*</span>' if required else ""
    return (f'<div class="wide"><label>{label}{req}</label>'
            f'<textarea name="{name}" rows="{rows}"'
            f' placeholder="{_esc(placeholder)}"{cls}>{val}</textarea></div>')


def _radio(state: WizardState, name: str, options: list[tuple[str, str]],
           errors: set | None = None, label: str = "",
           required: bool = False) -> str:
    cls = "radio-row invalid" if errors and name in errors else "radio-row"
    req = ' <span class="req">*</span>' if required else ""
    current = str(state.get(name, ""))
    rows = "".join(
        f'<label><input type="radio" name="{name}" value="{_esc(v)}"'
        f'{" checked" if current == v else ""}> {_esc(text)}</label>'
        for v, text in options)
    return f'<label>{label}{req}</label><div class="{cls}">{rows}</div>'


def _letters_ok(state: WizardState) -> set:
    """Field-error set for the cover-letters step (empty == valid)."""
    errors: set = set()
    families = state.get("families") or {}
    if not families:
        errors.add("family_0_name")
        errors.add("family_0_identity")
        errors.add("family_0_craft")
        return errors
    for i, (name, fam) in enumerate(families.items()):
        if not str(fam.get("identity", "")).strip():
            errors.add(f"family_{i}_identity")
        if not str(fam.get("craft", "")).strip():
            errors.add(f"family_{i}_craft")
    return errors


def _step_errors(idx: int, state: WizardState) -> set:
    key, _, required = STEPS[idx]
    errors = {f for f in required if not str(state.get(f, "")).strip()}
    if key == "letters":
        errors |= _letters_ok(state)
    return errors


def _render_step(idx: int, state: WizardState, token: str,
                 errors: set | None = None, notice: str = "") -> str:
    key, title, _ = STEPS[idx]
    e = errors or set()

    if key == "basics":
        body = f"""<h2>About you</h2>
<p class="hint">Used to fill name/contact fields on applications and sign your cover letters.</p>
<div class="grid">
{_inp(state, "first_name", "Alex", e, "First name", True)}
{_inp(state, "last_name", "Rivera", e, "Last name", True)}
{_inp(state, "email", "alex.rivera@example.com", e, "Email", True)}
{_inp(state, "phone", "+1 555 010 0100", e, "Phone", True)}
{_inp(state, "location", "Portland, OR", e, "Location")}
{_inp(state, "state", "Oregon", e, "State / region")}
{_inp(state, "phonetic_name", "AL-ex ri-VAIR-ah", e, "Phonetic name")}
{_inp(state, "pronouns", "they/them", e, "Pronouns")}
{_inp(state, "website", "https://alexrivera.example.com", e, "Portfolio / website")}
{_inp(state, "linkedin", "https://linkedin.com/in/your-handle", e, "LinkedIn")}
{_inp(state, "github", "https://github.com/your-handle", e, "GitHub")}
</div>"""
    elif key == "workauth":
        body = f"""<h2>Work authorization</h2>
<p class="hint">These answer the standard eligibility questions on every application &mdash; answer honestly, forms are legally binding.</p>
{_radio(state, "auth_status", [("yes", "Yes"),
                               ("yes_limited", "Yes, with time limit (e.g. work permit)"),
                               ("no", "No")], e,
        "Are you authorized to work in your target country?", True)}
<div style="height:14px"></div>
{_radio(state, "sponsorship", [("no", "No"), ("yes", "Yes")], e,
        "Will you now or in the future require sponsorship?", True)}
<div style="height:14px"></div>
<div class="grid">{_ta(state, "auth_notes",
    "e.g. Authorized through June 2028 on a post-study work permit\u2026", e,
    "Notes (visa type, expiry, anything a recruiter should know)")}</div>"""
    elif key == "targeting":
        checks = "".join(
            f'<label><input type="checkbox" name="sources" value="{k}"'
            f'{" checked" if k in (state.get("sources") or []) else ""}> '
            f'{k.capitalize()}</label>'
            for k in SOURCE_KINDS)
        body = f"""<h2>What are you looking for?</h2>
<p class="hint">Controls which postings get scanned, scored, and queued for your review.</p>
<div class="grid">
{_inp(state, "titles", "Product Designer, Design Engineer, UX Designer", e, "Target titles (comma-separated)", True, wide=True)}
{_inp(state, "skills", "prototyping, design systems, user research", e, "Skills that count in your favor", wide=True)}
{_inp(state, "exclude_keywords", "staff, principal, director, intern", e, "Exclude keywords", wide=True)}
<div>{_radio(state, "remote_ok", [("yes", "Yes"), ("no", "Onsite/hybrid only")], e, "Remote OK?")}</div>
{_inp(state, "locations", "Portland, San Francisco, Remote US", e, "Locations")}
<div class="wide"><label>Job boards to scan</label><div class="check-row">{checks}</div></div>
{_ta(state, "source_tokens", "greenhouse:examplecorp\nlever:samplestartup", e,
     "Company board tokens, one per line as kind:token", rows=3)}
</div>
<div class="note">Each ATS needs the company's board token (the slug in its careers URL). Add more later in config.yaml.</div>"""
    elif key == "resumes":
        rows = []
        variants = state.get("resume_variants") or []
        for i in range(3):
            v = variants[i] if i < len(variants) else {}
            rows.append(
                f'<div><label>Variant file</label>'
                f'<input type="text" name="variant_{i}_path"'
                f' value="{_esc(v.get("path", ""))}"'
                f' placeholder="design-engineer-resume.pdf"></div>'
                f'<div><label>&hellip;used when title contains</label>'
                f'<input type="text" name="variant_{i}_keywords"'
                f' value="{_esc(v.get("keywords", ""))}"'
                f' placeholder="design engineer, ux engineer"></div>')
        body = f"""<h2>Resume files</h2>
<p class="hint">One default resume is required. Add role-specific variants and the agent attaches the best match per job title.</p>
<div class="grid">
{_inp(state, "resume_default", "resume.pdf", e, "Default resume file (PDF, relative to your jobagent folder)", True, wide=True)}
{"".join(rows)}
</div>
<div class="note">Drop the PDF files into your jobagent folder with these exact names. Files are checked at fill time; a missing variant HOLDS the job instead of attaching the wrong resume.</div>"""
    elif key == "letters":
        fams = list((state.get("families") or {}).items())
        blocks = []
        for i in range(3):
            name, fam = (fams[i] if i < len(fams) else ("", {}))
            def fv(k):
                return _esc(fam.get(k, ""))
            cls_i = ' class="invalid"' if f"family_{i}_identity" in e else ""
            cls_c = ' class="invalid"' if f"family_{i}_craft" in e else ""
            cls_n = ' class="invalid"' if f"family_{i}_name" in e else ""
            blocks.append(f"""<div class="fam"><h3>Family {i + 1}{" (required)" if i == 0 else " (optional)"}</h3>
<div class="grid">
<div><label>Family id{' <span class="req">*</span>' if i == 0 else ''}</label>
<input type="text" name="family_{i}_name" value="{_esc(name)}" placeholder="product_designer"{cls_n}></div>
<div><label>Matched when title contains</label>
<input type="text" name="family_{i}_keywords" value="{fv('keywords')}" placeholder="design engineer, ux engineer"></div>
<div class="wide"><label>Identity paragraph{' <span class="req">*</span>' if i == 0 else ''}</label>
<textarea name="family_{i}_identity" rows="3" placeholder="I am a product designer who\u2026 (who you are, your foundation, what you care about)"{cls_i}>{fv('identity')}</textarea></div>
<div class="wide"><label>Craft paragraph{' <span class="req">*</span>' if i == 0 else ''}</label>
<textarea name="family_{i}_craft" rows="2" placeholder="A concrete sentence about how you work\u2026"{cls_c}>{fv('craft')}</textarea></div>
<div><label>Closing mix</label>
<input type="text" name="family_{i}_closing_mix" value="{fv('closing_mix')}" placeholder="design craft, systems thinking, hands-on implementation"></div>
<div><label>Validator marker</label>
<input type="text" name="family_{i}_marker" value="{fv('marker')}" placeholder="product designer"></div>
</div></div>""")
        projs = state.get("projects") or []
        prows = []
        for i in range(3):
            pr = projs[i] if i < len(projs) else {}
            prows.append(
                f'<div><label>Project keywords</label>'
                f'<input type="text" name="project_{i}_keywords"'
                f' value="{_esc(pr.get("keywords", ""))}" placeholder="ai, ios"></div>'
                f'<div class="wide"><label>Project story</label>'
                f'<textarea name="project_{i}_text" rows="2"'
                f' placeholder="Fieldnote is the closest example of how I work\u2026">'
                f'{_esc(pr.get("text", ""))}</textarea></div>')
        body = f"""<h2>Cover letter voices</h2>
<p class="hint">One family per role type you apply to. Grey text is example only &mdash; it is never submitted; write your own.</p>
{"".join(blocks)}
<div class="fam"><h3>Project stories (optional, matched by keyword)</h3>
<div class="grid">{"".join(prows)}</div></div>"""
    elif key == "facts":
        body = f"""<h2>Your facts file</h2>
<p class="hint">The agent only answers application questions it can ground in these facts &mdash; anything missing gets flagged for your review instead of guessed.</p>
<div class="grid">
{_ta(state, "facts_background", "Education, past roles, years of experience\u2026", e, "Background &amp; experience")}
{_ta(state, "facts_projects", "2\u20133 projects with your role and outcomes\u2026", e, "Projects you talk about")}
{_ta(state, "facts_standard", "Q: What are your salary expectations?\nA: \u2026", e, "Standard question answers (Q:/A: pairs)", rows=4)}
</div>"""
    else:  # review
        fam_names = ", ".join((state.get("families") or {}).keys()) or "none yet"
        srcs = ", ".join(state.get("sources") or []) or "none yet"
        body = f"""<h2>Review &amp; write files</h2>
<p class="hint">Nothing has been saved yet. This writes two files (existing ones are backed up first).</p>
<table class="review">
<tr><td>config.yaml</td><td>profile ({_esc(state.get('full_name') or (state.get('first_name', '') + ' ' + state.get('last_name', '')).strip() or 'no name yet')}), targeting, sources ({_esc(srcs)}), resumes, cover-letter families ({_esc(fam_names)})</td></tr>
<tr><td>answers.md</td><td>work authorization + your facts sections</td></tr>
</table>
<div class="note">Not covered here (see README): Slack approval bot token, email app password for verification codes, daily schedule. Secrets stay in <code>scripts/.env</code> &mdash; never in these files or this page.</div>"""

    chips = []
    for i, (_, t, _r) in enumerate(STEPS):
        cls = "step active" if i == idx else (
            "step done" if i < idx and not _step_errors(i, state) else "step")
        chips.append(f'<a class="{cls}" href="/setup?token={token}&step={i}">{t}</a>')

    err_html = ""
    if e:
        err_html = ('<span class="errmsg">Please fill the required fields '
                    'marked * before continuing.</span>')
    if key == "review":
        nav = (f'<a class="btn" href="/setup?token={token}&step={idx - 1}">'
               f'&larr; Back</a>{err_html}'
               f'<form method="post" action="/finish?token={token}" '
               f'style="margin:0"><button class="btn primary" type="submit">'
               f'Write config.yaml + answers.md</button></form>')
        form_open, form_close = "", ""
    else:
        back = (f'<a class="btn" href="/setup?token={token}&step={idx - 1}">'
                f'&larr; Back</a>' if idx > 0 else "<span></span>")
        nav = (f'{back}{err_html}'
               f'<button class="btn primary" type="submit">Next &rarr;</button>')
        form_open = f'<form method="post" action="/setup?token={token}&step={idx}">'
        form_close = "</form>"

    style = _STYLE + (_STYLE_ERR if e else "")
    notice_html = f'<div class="note">{_esc(notice)}</div>' if notice else ""
    return f"""<!doctype html><html><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>jobagent setup</title><style>{style}</style></head><body>
<div class="frame"><div class="app">
<header class="bar"><h1>jobagent setup</h1>
<div class="url">local only &mdash; nothing leaves your machine</div></header>
<nav class="steps">{"".join(chips)}</nav>
{form_open}<main>{notice_html}{body}</main>
<footer class="nav">{nav}</footer>{form_close}
</div></div></body></html>"""


def _render_done(written: list[str], baks: list[str], token: str) -> str:
    files = "".join(f"<li><code>{_esc(w)}</code></li>" for w in written)
    bak_html = ""
    if baks:
        bak_html = ("<p class=\"hint\">Previous versions were backed up: "
                    + ", ".join(f"<code>{_esc(b)}</code>" for b in baks)
                    + "</p>")
    return f"""<!doctype html><html><head><meta charset="utf-8">
<title>jobagent setup — done</title><style>{_STYLE}</style></head><body>
<div class="frame"><div class="app">
<header class="bar"><h1>Setup complete</h1></header>
<main>
<h2>Files written</h2>
<ul>{files}</ul>
{bak_html}
<div class="note"><b>Next steps</b><br>
1. Drop your resume PDF(s) into the folder with the names you entered.<br>
2. Optional: Slack approvals + email verification &mdash; copy
<code>scripts/.env.example</code> to <code>scripts/.env</code> and follow the
README (secrets never go through this wizard).<br>
3. Try it: <code>jobagent scan --config config.yaml</code> &mdash; scanning is
read-only and submits nothing.</div>
<p class="hint" style="margin-top:14px">You can re-run
<code>jobagent setup</code> any time to edit these answers. This wizard is
still running &mdash; press Ctrl-C in the terminal to stop it, or just close
this tab.</p>
</main>
</div></div></body></html>"""


class _WizardHandler(BaseHTTPRequestHandler):
    session: dict = {}

    def log_message(self, fmt, *args):  # quiet server
        pass

    def _deny(self):
        self.send_response(403)
        self.send_header("Content-Type", "text/plain; charset=utf-8")
        self.end_headers()
        self.wfile.write(b"Forbidden: bad or missing token")

    def _page(self, html_text: str, status: int = 200):
        data = html_text.encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.send_header("Content-Length", str(len(data)))
        self.end_headers()
        self.wfile.write(data)

    def _check_token(self, qs: dict) -> bool:
        return (qs.get("token") or [""])[0] == self.session["token"]

    def do_GET(self):
        url = urlparse(self.path)
        qs = parse_qs(url.query)
        if not self._check_token(qs):
            return self._deny()
        state = self.session["state"]
        token = self.session["token"]
        if url.path in ("/", "/setup"):
            try:
                idx = max(0, min(len(STEPS) - 1,
                                 int((qs.get("step") or ["0"])[0])))
            except ValueError:
                idx = 0
            return self._page(_render_step(idx, state, token))
        self._page("<h1>Not found</h1>", 404)

    def do_POST(self):
        url = urlparse(self.path)
        qs = parse_qs(url.query)
        if not self._check_token(qs):
            return self._deny()
        state = self.session["state"]
        token = self.session["token"]
        length = int(self.headers.get("Content-Length") or 0)
        body = self.rfile.read(length) if length else b""
        ctype = self.headers.get("Content-Type") or ""

        if url.path == "/finish":
            cfg_path = Path(self.session["config_path"])
            ans_path = cfg_path.parent / "answers.md"
            before = {p.name for p in cfg_path.parent.glob("*.bak-*")}
            written = write_outputs(state, cfg_path, ans_path)
            baks = sorted(
                p.name for p in cfg_path.parent.glob("*.bak-*")
                if p.name not in before)
            return self._page(_render_done(written, baks, token))

        if url.path != "/setup":
            return self._page("<h1>Not found</h1>", 404)

        try:
            idx = max(0, min(len(STEPS) - 1, int((qs.get("step") or ["0"])[0])))
        except ValueError:
            idx = 0

        if ctype.startswith("multipart/form-data"):
            parts = _parse_multipart(body, ctype)
            fields = {}
            for name, (fname, data) in parts.items():
                if name == "resume_file" and fname:
                    saved = _save_resume(
                        Path(self.session["config_path"]).parent, fname, data)
                    if saved:
                        fields["resume_default"] = saved
                elif not fname:
                    fields[name] = [data.decode("utf-8", "replace")]
            form = fields
        else:
            form = parse_qs(body.decode("utf-8", "replace"),
                            keep_blank_values=True)

        _apply_form(idx, form, state)
        errors = _step_errors(idx, state)
        if errors:
            return self._page(_render_step(idx, state, token, errors=errors))
        nxt = min(len(STEPS) - 1, idx + 1)
        return self._page(_render_step(nxt, state, token))


def _apply_form(idx: int, form: dict, state: WizardState) -> None:
    """Merge one step's POSTed fields into the wizard state."""
    key = STEPS[idx][0]

    def first(name: str) -> str:
        return (form.get(name) or [""])[0]

    simple = {
        "basics": ["first_name", "last_name", "email", "phone", "location",
                   "state", "phonetic_name", "pronouns", "website",
                   "linkedin", "github"],
        "workauth": ["auth_status", "sponsorship", "auth_notes"],
        "targeting": ["titles", "skills", "exclude_keywords", "remote_ok",
                      "locations", "source_tokens"],
        "resumes": ["resume_default"],
        "facts": ["facts_background", "facts_projects", "facts_standard"],
    }.get(key, [])
    for name in simple:
        if name in form:
            state[name] = first(name)
    if key == "basics":
        state["full_name"] = (
            f"{state.get('first_name', '')} {state.get('last_name', '')}"
        ).strip()
    if key == "targeting":
        state["sources"] = [
            s for s in (form.get("sources") or []) if s in SOURCE_KINDS]
    if key == "resumes":
        variants = []
        for i in range(3):
            path = first(f"variant_{i}_path").strip()
            if path:
                variants.append({
                    "path": path,
                    "keywords": first(f"variant_{i}_keywords"),
                })
        state["resume_variants"] = variants
    if key == "letters":
        families: dict = {}
        for i in range(3):
            name = re.sub(r"[^a-z0-9_]", "",
                          first(f"family_{i}_name").strip().lower()
                          .replace(" ", "_"))
            if not name:
                continue
            families[name] = {
                "keywords": first(f"family_{i}_keywords"),
                "identity": first(f"family_{i}_identity"),
                "craft": first(f"family_{i}_craft"),
                "closing_mix": first(f"family_{i}_closing_mix"),
                "marker": (first(f"family_{i}_marker").strip().lower()
                           or name.replace("_", " ")),
            }
        state["families"] = families
        projects = []
        for i in range(3):
            text = first(f"project_{i}_text").strip()
            if text:
                projects.append({
                    "keywords": first(f"project_{i}_keywords"),
                    "text": text,
                })
        state["projects"] = projects


def _parse_multipart(body: bytes, content_type: str) -> dict[str, tuple[str, bytes]]:
    """name -> (filename, data) for a multipart/form-data body. Minimal:
    enough for one small PDF + text fields, not a general parser."""
    m = re.search(r'boundary="?([^";]+)"?', content_type)
    if not m:
        return {}
    boundary = b"--" + m.group(1).encode()
    out: dict[str, tuple[str, bytes]] = {}
    for part in body.split(boundary):
        if b"\r\n\r\n" not in part:
            continue
        head, _, data = part.partition(b"\r\n\r\n")
        data = data.rstrip(b"\r\n-")
        name_m = re.search(rb'name="([^"]+)"', head)
        if not name_m:
            continue
        file_m = re.search(rb'filename="([^"]*)"', head)
        fname = file_m.group(1).decode("utf-8", "replace") if file_m else ""
        out[name_m.group(1).decode()] = (fname, data)
    return out


def _save_resume(dest_dir: Path, filename: str, data: bytes) -> str:
    """Save an uploaded resume PDF next to config.yaml. Returns the saved
    basename, or '' when rejected (wrong type / too large / empty)."""
    base = os.path.basename(filename).strip()
    if not base.lower().endswith(".pdf") or not data:
        return ""
    if len(data) > 10 * 1024 * 1024:
        return ""
    base = re.sub(r"[^A-Za-z0-9._ -]", "_", base)
    dest_dir.mkdir(parents=True, exist_ok=True)
    (dest_dir / base).write_bytes(data)
    return base


def _make_server(config_path: str, host: str = "127.0.0.1", port: int = 0):
    """(server, token, url). Exposed for tests; run_setup_wizard drives it."""
    cfg_path = Path(config_path)
    token = os.getenv("JOBAGENT_SETUP_TOKEN") or token_urlsafe(24)
    state = state_from_existing(cfg_path, cfg_path.parent / "answers.md")

    handler = type("BoundWizardHandler", (_WizardHandler,), {
        "session": {"token": token, "state": state,
                    "config_path": str(cfg_path)},
    })
    server = ThreadingHTTPServer((host, port), handler)
    url = f"http://{host}:{server.server_address[1]}/setup?token={token}&step=0"
    return server, token, url


def run_setup_wizard(config_path: str, host: str = "127.0.0.1",
                     port: int = 0, open_browser: bool = True) -> None:
    server, _token, url = _make_server(config_path, host=host, port=port)
    print("jobagent setup wizard running (local only):")
    print(f"  {url}")
    print("Press Ctrl-C when you are done.")
    if open_browser:
        threading.Timer(0.3, webbrowser.open, args=(url,)).start()
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nsetup wizard stopped")
    finally:
        server.server_close()
